export const GET_ALL_ARTICLES_REQUESTED = 'GET_ALL_ARTICLES_REQUESTED';
export const GET_ALL_ARTICLES_SUCCESS = 'GET_ALL_ARTICLES_SUCCESS';
export const GET_ALL_ARTICLES_FAIL = 'GET_ALL_ARTICLES_FAIL';

export const SAVE_NEW_ARTICLE_REQUESTED = 'SAVE_NEW_ARTICLE_REQUESTED';
export const SAVE_NEW_ARTICLE_REQUESTED_SUCCESS =
  'SAVE_NEW_ARTICLE_REQUESTED_SUCCESS';
export const SAVE_NEW_ARTICLE_REQUESTED_FAIL =
  'SAVE_NEW_ARTICLE_REQUESTED_FAIL';

export const GET_ARTICLE_BY_ID_REQUESTED = 'GET_ARTICLE_BY_ID_REQUESTED';
export const GET_ARTICLE_BY_ID_SUCCESS = 'GET_ARTICLE_BY_ID_SUCCESS';
export const GET_ARTICLE_BY_ID_FAIL = 'GET_ARTICLE_BY_ID_FAIL';

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';
export const SET_USER = 'SET_USER';

export const POST_COMMENT_REQUESTED = 'POST_COMMENT_REQUESTED';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_FAIL = 'POST_COMMENT_FAIL';

export const DELETE_COMMENT_REQUESTED = 'DELETE_COMMENT_REQUESTED';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';
